version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meudinheiro
      PGDATA: /tmp
    volumes:
       - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - postgres
  

networks:
  postgres:
    driver: bridge
 